export const ALL_SALE_PRODUCT_REQUEST="ALL_SALE_PRODUCT_REQUEST";
export const ALL_SALE_PRODUCT_SUCCESS="ALL_SALE_PRODUCT_SUCCESS";
export const ALL_SALE_PRODUCT_FAIL="ALL_SALE_PRODUCT_FAIL";



export const  SALE_PRODUCT_DETAIL_REQUEST="SALE_PRODUCT_DETAIL_REQUEST";
export const  SALE_PRODUCT_DETAIL_FAIL="SALE_PRODUCT_DETAIL_FAIL";
export const  SALE_PRODUCT_DETAIL_SUCCESS="SALE_PRODUCT_DETAIL_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
